using wServer.logic.behaviors;
using wServer.logic.loot;
using wServer.logic.transitions;

namespace wServer.logic
{
    partial class BehaviorDb
    {
        private _ VoidEntity = () => Behav()
            .Init("1LH Void Entity",
                 new State(
                    new ScaleHP(4000),
                    new DropPortalOnDeath("Glowing Realm Portal", 100, PortalDespawnTimeSec: 360),
                    new State(
                    new PlayerWithinTransition(8, "1Begin")
                        ),
                 new State("1Begin",
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new Taunt("So, I've noticed you've gotten past my Cultist and my Marble Colossus?"),
                    new TimedTransition(2000, "2Begin")
                        ),
                 new State("2Begin",
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new Taunt("This fight won't be as easy as those 2! You'll die in a place where nothing is remembered!"),
                    new TimedTransition(2000, "3Begin")
                        ),
                  new State("3Begin",
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new Flash(0x00FF00, 0.25, 12),
                    new Order(50, "1LH VOID INVISS", "spawn"),
                    new TimedTransition(2000, "4Begin")
                        ),
                  new State("4Begin",
                    new Taunt("Members of the Void, kill these mortals!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new EntitiesNotExistsTransition(10000, "5Begin", "Entity Protector")
                      ),
                    new State("5Begin",
                    new Taunt("Is that how it's going to be?!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "6Begin")
                          ),
                    new State("6Begin",
                    new Taunt("Lets take you to ur limit!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "7Begin")
                           ),
                  new State("7Begin",
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new Flash(0x00FF00, 0.25, 12),
                    new Order(50, "1LH VOID INVISS", "spawn2"),
                    new TimedTransition(2000, "8Begin")
                           ),
                  new State("8Begin",
                    new Taunt("Lets take you to ur limit!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new EntitiesNotExistsTransition(10000, "9Begin", "Entity Protector")
                           ),
                  new State("9Begin",
                    new Flash(0x00FF00, 0.25, 12),
                    new Taunt("Okay, This has gone on long enough!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "10Begin")
                           ),
                  new State("10Begin",
                      new HpLessTransition(0.80, "13Begin"),
                     new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 160, coolDownOffset: 1400, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 170, coolDownOffset: 1600, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 180, coolDownOffset: 1800, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 180, coolDownOffset: 2000, shootAngle: 45),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 180, coolDownOffset: 0, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 170, coolDownOffset: 200, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 160, coolDownOffset: 400, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 150, coolDownOffset: 600, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 140, coolDownOffset: 800, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 130, coolDownOffset: 1000, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 120, coolDownOffset: 1200, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 110, coolDownOffset: 1400, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 3, coolDown: 2575, fixedAngle: 100, coolDownOffset: 1600, shootAngle: 90),
                    new TimedTransition(5200, "11Begin")
                      ),
                   new State("11Begin",
                       new HpLessTransition(0.80, "13Begin"),
                     new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 160, coolDownOffset: 1400, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 170, coolDownOffset: 1600, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 180, coolDownOffset: 1800, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 180, coolDownOffset: 2000, shootAngle: 45),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 180, coolDownOffset: 0, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 170, coolDownOffset: 200, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 160, coolDownOffset: 400, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 150, coolDownOffset: 600, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 140, coolDownOffset: 800, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 130, coolDownOffset: 1000, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 120, coolDownOffset: 1200, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 110, coolDownOffset: 1400, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 2575, fixedAngle: 100, coolDownOffset: 1600, shootAngle: 90),
                    new TimedTransition(5200, "12Begin")
                                ),
                  new State("12Begin",
                      new HpLessTransition(0.80, "13Begin"),
                 new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 160, coolDownOffset: 1400, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 170, coolDownOffset: 1600, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 180, coolDownOffset: 1800, shootAngle: 90),
                            new Shoot(1, 8, projectileIndex: 2, coolDown: 4575, fixedAngle: 180, coolDownOffset: 2000, shootAngle: 45),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 180, coolDownOffset: 0, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 170, coolDownOffset: 200, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 160, coolDownOffset: 400, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 150, coolDownOffset: 600, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 140, coolDownOffset: 800, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 130, coolDownOffset: 1000, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 120, coolDownOffset: 1200, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 110, coolDownOffset: 1400, shootAngle: 90),
                            new Shoot(1, 4, projectileIndex: 2, coolDown: 4575, fixedAngle: 100, coolDownOffset: 1600, shootAngle: 90),
                    new TimedTransition(5200, "10Begin")
                             ),
                    new State("13Begin",
                    new Flash(0xffffff, 0.25, 12),
                    new Taunt("The void has infinite power. Your attacks are nothing to me!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(1500, "14Begin")
                              ),
                  new State("14Begin",
                   new Wander(.01),
                        new Shoot(25, projectileIndex: 0, count: 8, shootAngle: 45, coolDown: 1500, coolDownOffset: 1500),
                        new Shoot(25, projectileIndex: 1, count: 3, shootAngle: 10, coolDown: 1000, coolDownOffset: 1000),
                        new Shoot(25, projectileIndex: 2, count: 3, shootAngle: 10, coolDown: 1000,
                            coolDownOffset: 1000),
                        new Shoot(25, projectileIndex: 3, count: 2, shootAngle: 10, coolDown: 1000,
                            coolDownOffset: 1000),
                        new Shoot(25, projectileIndex: 4, count: 3, shootAngle: 10, coolDown: 1000,
                            coolDownOffset: 1000),
                        new Shoot(25, projectileIndex: 5, count: 2, shootAngle: 10, coolDown: 1000,
                            coolDownOffset: 1000),
                        new Shoot(25, projectileIndex: 6, count: 3, shootAngle: 10, coolDown: 1000,
                            coolDownOffset: 1000),
                            new HpLessTransition(0.70, "15Begin")
                           ),
                    new State("15Begin",
                    new Flash(0xffffff, 0.25, 12),
                    new Taunt("This is still just the beginning!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "16Begin")
                        ),
                      new State("16Begin",
                          new HpLessTransition(0.50, "18Begin"),
                           new StayBack(0.2, 2),
                        new Shoot(10, count: 5, shootAngle: 28, projectileIndex: 2, coolDown: 600),
                        new Shoot(10, count: 12, shootAngle: 24, projectileIndex: 3, coolDown: 1200),
                    new TimedTransition(5000, "17Begin")
                            ),
                      new State("17Begin",
                          new HpLessTransition(0.50, "18Begin"),
                        new Shoot(50, 3, projectileIndex: 5, coolDown: 1500, coolDownOffset: 200),
                        new Shoot(50, 10, projectileIndex: 3, coolDown: 2000, coolDownOffset: 200),
                        new Shoot(50, 10, projectileIndex: 1, coolDown: 500, coolDownOffset: 200),
                    new TimedTransition(5000, "16Begin")
                              ),
                    new State("18Begin",
                    new Flash(0xffffff, 0.25, 12),
                    new Taunt("ENOUGH! from now on i'm not holding back!", "ENOUGH! You will be erased without a warning!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "1")
                        ),
                 new State("1",
                    new Shoot(10, projectileIndex: 0, count: 10, shootAngle: 10, fixedAngle: 0),
                    new Shoot(10, projectileIndex: 0, count: 10, shootAngle: 10, fixedAngle: 180),
                    new Shoot(50, projectileIndex: 4, count: 6, shootAngle: 60, fixedAngle: 4, coolDown: 1000, predictive: 0.1),
                    new HpLessTransition(0.25, "3"),
                    new TimedTransition(2500, "2")
                        ),
                 new State("2",
                    new Shoot(10, projectileIndex: 0, count: 10, shootAngle: 10, fixedAngle: 270),
                    new Shoot(10, projectileIndex: 0, count: 10, shootAngle: 10, fixedAngle: 90),
                     new Shoot(50, projectileIndex: 4, count: 6, shootAngle: 60, fixedAngle: 4, coolDown: 1000, predictive: 0.1),
                    new HpLessTransition(0.25, "3"),
                    new TimedTransition(2500, "1")
                                ),
                    new State("3",
                    new Flash(0xff0000, 1, 50),
                    new Taunt("THERES NO WAY I'M LOSING TO YOU PATHETIC MORTALS!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "4")
                        ),
                    new State("4",
                        new Taunt("MY FURY ISN'T OVER!", "TASTE MY INFINITE WRATH", "THIS WILL BE A BLOODY DEATH FOR YOU", "NOTHING CAN SAVE YOU NOW", "MY WRATH IS INFINITE", "MY POWER HAS NO END", "THIS FIGHT IS OVER! YOU'VE LOST"),
                    new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 3, coolDown: 10800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 4, coolDown: 10800),
                            new Shoot(50, projectileIndex: 4, count: 1, shootAngle: 60, fixedAngle: 4, coolDown: 1000, predictive: 0.1),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 6, coolDown: 10800, coolDownOffset: 200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 7, coolDown: 10800, coolDownOffset: 200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 9, coolDown: 10800, coolDownOffset: 400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 10, coolDown: 10800, coolDownOffset: 400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 12, coolDown: 10800, coolDownOffset: 600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 13, coolDown: 10800, coolDownOffset: 600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 15, coolDown: 10800, coolDownOffset: 800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 16, coolDown: 10800, coolDownOffset: 800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 18, coolDown: 10800, coolDownOffset: 1000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 19, coolDown: 10800, coolDownOffset: 1000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 21, coolDown: 10800, coolDownOffset: 1200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 22, coolDown: 10800, coolDownOffset: 1200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 24, coolDown: 10800, coolDownOffset: 1400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 25, coolDown: 10800, coolDownOffset: 1400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 27, coolDown: 10800, coolDownOffset: 1600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 28, coolDown: 10800, coolDownOffset: 1600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 30, coolDown: 10800, coolDownOffset: 1800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 31, coolDown: 10800, coolDownOffset: 1800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 33, coolDown: 10800, coolDownOffset: 2000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 34, coolDown: 10800, coolDownOffset: 2000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 36, coolDown: 10800, coolDownOffset: 2200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 37, coolDown: 10800, coolDownOffset: 2200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 39, coolDown: 10800, coolDownOffset: 2400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 40, coolDown: 10800, coolDownOffset: 2400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 42, coolDown: 10800, coolDownOffset: 2600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 43, coolDown: 10800, coolDownOffset: 2600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 45, coolDown: 10800, coolDownOffset: 2800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 46, coolDown: 10800, coolDownOffset: 2800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 48, coolDown: 10800, coolDownOffset: 3000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 49, coolDown: 10800, coolDownOffset: 3000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 51, coolDown: 10800, coolDownOffset: 3200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 52, coolDown: 10800, coolDownOffset: 3200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 54, coolDown: 10800, coolDownOffset: 3400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 55, coolDown: 10800, coolDownOffset: 3400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 57, coolDown: 10800, coolDownOffset: 3600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 58, coolDown: 10800, coolDownOffset: 3600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 60, coolDown: 10800, coolDownOffset: 3800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 61, coolDown: 10800, coolDownOffset: 3800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 63, coolDown: 10800, coolDownOffset: 4000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 64, coolDown: 10800, coolDownOffset: 4000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 66, coolDown: 10800, coolDownOffset: 4200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 67, coolDown: 10800, coolDownOffset: 4200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 69, coolDown: 10800, coolDownOffset: 4400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 70, coolDown: 10800, coolDownOffset: 4400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 72, coolDown: 10800, coolDownOffset: 4600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 73, coolDown: 10800, coolDownOffset: 4600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 75, coolDown: 10800, coolDownOffset: 4800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 76, coolDown: 10800, coolDownOffset: 4800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 78, coolDown: 10800, coolDownOffset: 5000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 79, coolDown: 10800, coolDownOffset: 5000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 81, coolDown: 10800, coolDownOffset: 5200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 82, coolDown: 10800, coolDownOffset: 5200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 84, coolDown: 10800, coolDownOffset: 5400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 85, coolDown: 10800, coolDownOffset: 5400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 87, coolDown: 10800, coolDownOffset: 5600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 88, coolDown: 10800, coolDownOffset: 5600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 90, coolDown: 10800, coolDownOffset: 5800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 91, coolDown: 10800, coolDownOffset: 5800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 93, coolDown: 10800, coolDownOffset: 6000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 94, coolDown: 10800, coolDownOffset: 6000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 96, coolDown: 10800, coolDownOffset: 6200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 97, coolDown: 10800, coolDownOffset: 6200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 99, coolDown: 10800, coolDownOffset: 6400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 100, coolDown: 10800, coolDownOffset: 6400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 102, coolDown: 10800, coolDownOffset: 6600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 103, coolDown: 10800, coolDownOffset: 6600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 105, coolDown: 10800, coolDownOffset: 6800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 106, coolDown: 10800, coolDownOffset: 6800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 108, coolDown: 10800, coolDownOffset: 7000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 109, coolDown: 10800, coolDownOffset: 7000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 111, coolDown: 10800, coolDownOffset: 7200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 112, coolDown: 10800, coolDownOffset: 7200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 114, coolDown: 10800, coolDownOffset: 7400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 115, coolDown: 10800, coolDownOffset: 7400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 117, coolDown: 10800, coolDownOffset: 7600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 118, coolDown: 10800, coolDownOffset: 7600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 120, coolDown: 10800, coolDownOffset: 7800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 121, coolDown: 10800, coolDownOffset: 7800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 123, coolDown: 10800, coolDownOffset: 8000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 124, coolDown: 10800, coolDownOffset: 8000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 126, coolDown: 10800, coolDownOffset: 8200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 127, coolDown: 10800, coolDownOffset: 8200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 129, coolDown: 10800, coolDownOffset: 8400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 130, coolDown: 10800, coolDownOffset: 8400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 132, coolDown: 10800, coolDownOffset: 8600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 133, coolDown: 10800, coolDownOffset: 8600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 135, coolDown: 10800, coolDownOffset: 8800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 136, coolDown: 10800, coolDownOffset: 8800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 138, coolDown: 10800, coolDownOffset: 9000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 139, coolDown: 10800, coolDownOffset: 9000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 141, coolDown: 10800, coolDownOffset: 9200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 142, coolDown: 10800, coolDownOffset: 9200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 144, coolDown: 10800, coolDownOffset: 9400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 145, coolDown: 10800, coolDownOffset: 9400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 147, coolDown: 10800, coolDownOffset: 9600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 148, coolDown: 10800, coolDownOffset: 9600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 150, coolDown: 10800, coolDownOffset: 9800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 151, coolDown: 10800, coolDownOffset: 9800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 153, coolDown: 10800, coolDownOffset: 10000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 154, coolDown: 10800, coolDownOffset: 10000),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 156, coolDown: 10800, coolDownOffset: 10200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 157, coolDown: 10800, coolDownOffset: 10200),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 159, coolDown: 10800, coolDownOffset: 10400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 160, coolDown: 10800, coolDownOffset: 10400),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 162, coolDown: 10800, coolDownOffset: 10600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 163, coolDown: 10800, coolDownOffset: 10600),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 165, coolDown: 10800, coolDownOffset: 10800),
                            new Shoot(50, projectileIndex: 4, count: 8, shootAngle: 60, fixedAngle: 166, coolDown: 10800, coolDownOffset: 10800),
                            new HpLessTransition(0.05, "5"),
                            new TimedTransition(10800, "Hahaha")
                            ),
                        new State("Hahaha",
                            new Flash(0xffffff, 10, 1),
                            new Taunt("I can't feel my body!", "I need to cool down for a second.", "I can't hold this much energy!", "My body is numb!", "I'm suppose to be immortal!", "What is happening?"),
                            new HpLessTransition(0.05, "5"),
                            new TimedTransition(6000, "4")
                               ),
                    new State("5",
                    new Flash(0xffffff, 0.25, 12),
                    new Taunt("Perhaps I was wrong about you!", "This fight isn't over! I must escape for now.", "I've fallen to mortals, I know what I must do!"),
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new TimedTransition(2000, "6")

                             ),
                    new State("6",
                    new ConditionalEffect(ConditionEffectIndex.Invulnerable),
                    new Suicide()

                         )
                         )
            ,
                  new MostDamagers(9,
                    new ItemLoot("Greater Potion of Life", 1),
                    new ItemLoot("Void Loot Bag", 0.5),
                    new ItemLoot("Sourcestone", 0.01),
                    new ItemLoot("Armor of Nil", 0.01),
                    new ItemLoot("Darken Matter Quiver", 0.01),
                    new ItemLoot("Bow of the Void", 0.01),
                    new ItemLoot("Omnipotence Ring", 0.01)
                    ),

                       new MostDamagers(10,
                    new ItemLoot("Greater Potion of Mana", 1),
                    new ItemLoot("Greater Potion of Life", 1)
                           ),
                new MostDamagers(30,
                    new ItemLoot("Potion of Mana", 1),
                    new ItemLoot("Potion of Life", 1),
                    new ItemLoot("Potion of Life", 1)
                     )



            )


         .Init("1LH VOID INVISS",
                new State(
                    new State(
                        ),
                    new State("wait"
                        ),
                    new State("spawn",
                        new TossObject("Entity Protector", 0, 0, coolDown: 9999999, randomToss: false)
                           ),
                    new State("spawn2",
                        new TossObject("Entity Protector", 0, 0, coolDown: 9999999, randomToss: false),
                        new TossObject("Entity Protector", 0, 0, coolDown: 9999999, randomToss: false)
                        )
                    )
            )
         .Init("Entity Protector",
                new State(
                    new ScaleHP(2000),
                    new State("Tough",
                        new Follow(0.35, 8, 1),
                        new Shoot(8.4, count: 6, shootAngle: 60, projectileIndex: 1, coolDown: 2000),
                        new Shoot(8.4, count: 6, projectileIndex: 0, coolDown: 1300),
                        new HpLessTransition(0.35, "Scrub")
                        ),
                    new State("Scrub",
                        new StayBack(0.75, 5),
                        new Shoot(8.4, count: 6, shootAngle: 60, projectileIndex: 1, coolDown: 2000),
                        new Shoot(8.4, count: 5, projectileIndex: 0, coolDown: 1300)
                        )
                )
                    )
            ;
    }
}